export type Subject = "math" | "english";
export type Difficulty = "easy" | "medium" | "hard";

export type Question = {
  id: number;
  subject: Subject;
  category: string;
  difficulty: Difficulty;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
};

export const questionBank: Question[] = [
  {
    id: 1,
    subject: "math",
    category: "addition",
    difficulty: "easy",
    question: "What is 5 + 3?",
    options: ["6", "7", "8", "9"],
    correctAnswer: 2,
    explanation: "5 + 3 makes 8.",
  },
  {
    id: 2,
    subject: "math",
    category: "addition",
    difficulty: "easy",
    question: "You have 4 apples and get 2 more. How many apples?",
    options: ["5", "6", "7", "8"],
    correctAnswer: 1,
    explanation: "4 + 2 = 6 apples.",
  },
  {
    id: 3,
    subject: "math",
    category: "addition",
    difficulty: "medium",
    question: "What is 17 + 8?",
    options: ["24", "25", "26", "27"],
    correctAnswer: 1,
    explanation: "17 + 8 = 25.",
  },
  {
    id: 4,
    subject: "math",
    category: "addition",
    difficulty: "easy",
    question: "What is 9 + 6?",
    options: ["13", "14", "15", "16"],
    correctAnswer: 2,
    explanation: "9 + 6 = 15.",
  },
  {
    id: 5,
    subject: "math",
    category: "addition",
    difficulty: "easy",
    question: "What is 7 + 7?",
    options: ["12", "13", "14", "15"],
    correctAnswer: 2,
    explanation: "7 + 7 = 14.",
  },
  {
    id: 6,
    subject: "math",
    category: "subtraction",
    difficulty: "easy",
    question: "What is 10 − 4?",
    options: ["5", "6", "7", "8"],
    correctAnswer: 1,
    explanation: "10 − 4 = 6.",
  },
  {
    id: 7,
    subject: "math",
    category: "subtraction",
    difficulty: "easy",
    question: "What is 12 − 5?",
    options: ["6", "7", "8", "9"],
    correctAnswer: 1,
    explanation: "12 − 5 = 7.",
  },
  {
    id: 8,
    subject: "math",
    category: "subtraction",
    difficulty: "medium",
    question: "What is 32 − 18?",
    options: ["12", "13", "14", "15"],
    correctAnswer: 2,
    explanation: "32 − 18 = 14.",
  },
  {
    id: 9,
    subject: "math",
    category: "subtraction",
    difficulty: "easy",
    question: "There are 9 birds. 3 fly away. How many are left?",
    options: ["5", "6", "7", "8"],
    correctAnswer: 1,
    explanation: "9 − 3 = 6 birds.",
  },
  {
    id: 10,
    subject: "math",
    category: "subtraction",
    difficulty: "easy",
    question: "What is 15 − 7?",
    options: ["6", "7", "8", "9"],
    correctAnswer: 2,
    explanation: "15 − 7 = 8.",
  },
  {
    id: 11,
    subject: "math",
    category: "multiplication",
    difficulty: "easy",
    question: "What is 3 × 4?",
    options: ["7", "10", "12", "14"],
    correctAnswer: 2,
    explanation: "3 groups of 4 make 12.",
  },
  {
    id: 12,
    subject: "math",
    category: "multiplication",
    difficulty: "easy",
    question: "What is 5 × 2?",
    options: ["7", "8", "10", "12"],
    correctAnswer: 2,
    explanation: "5 groups of 2 make 10.",
  },
  {
    id: 13,
    subject: "math",
    category: "multiplication",
    difficulty: "medium",
    question: "What is 8 × 3?",
    options: ["21", "24", "26", "28"],
    correctAnswer: 1,
    explanation: "8 × 3 = 24.",
  },
  {
    id: 14,
    subject: "math",
    category: "multiplication",
    difficulty: "easy",
    question: "What is 2 × 6?",
    options: ["8", "10", "12", "14"],
    correctAnswer: 2,
    explanation: "2 × 6 = 12.",
  },
  {
    id: 15,
    subject: "math",
    category: "multiplication",
    difficulty: "easy",
    question: "How many wheels are on 3 bicycles?",
    options: ["3", "5", "6", "9"],
    correctAnswer: 2,
    explanation: "3 bicycles × 2 wheels = 6 wheels.",
  },
  {
    id: 16,
    subject: "math",
    category: "division",
    difficulty: "easy",
    question: "What is 12 ÷ 3?",
    options: ["3", "4", "5", "6"],
    correctAnswer: 1,
    explanation: "12 shared into 3 equal groups gives 4.",
  },
  {
    id: 17,
    subject: "math",
    category: "division",
    difficulty: "easy",
    question: "What is 20 ÷ 5?",
    options: ["2", "4", "5", "10"],
    correctAnswer: 1,
    explanation: "20 ÷ 5 = 4.",
  },
  {
    id: 18,
    subject: "math",
    category: "division",
    difficulty: "medium",
    question: "What is 36 ÷ 6?",
    options: ["5", "6", "7", "8"],
    correctAnswer: 1,
    explanation: "36 ÷ 6 = 6.",
  },
  {
    id: 19,
    subject: "math",
    category: "division",
    difficulty: "easy",
    question: "8 cookies are shared by 2 friends. How many each?",
    options: ["2", "3", "4", "6"],
    correctAnswer: 2,
    explanation: "8 ÷ 2 = 4 cookies each.",
  },
  {
    id: 20,
    subject: "math",
    category: "division",
    difficulty: "easy",
    question: "What is 15 ÷ 3?",
    options: ["3", "4", "5", "6"],
    correctAnswer: 2,
    explanation: "15 ÷ 3 = 5.",
  },
  {
    id: 21,
    subject: "math",
    category: "series",
    difficulty: "easy",
    question: "What number comes next: 2, 4, 6, __?",
    options: ["7", "8", "9", "10"],
    correctAnswer: 1,
    explanation: "The numbers go up by 2, so 8 is next.",
  },
  {
    id: 22,
    subject: "math",
    category: "series",
    difficulty: "easy",
    question: "What number comes next: 5, 10, 15, __?",
    options: ["18", "19", "20", "25"],
    correctAnswer: 2,
    explanation: "The numbers go up by 5, so 20 is next.",
  },
  {
    id: 23,
    subject: "math",
    category: "series",
    difficulty: "medium",
    question: "What number comes next: 3, 6, 9, __?",
    options: ["10", "11", "12", "13"],
    correctAnswer: 2,
    explanation: "The numbers go up by 3, so 12 is next.",
  },
  {
    id: 24,
    subject: "math",
    category: "series",
    difficulty: "easy",
    question: "What number comes next: 10, 20, 30, __?",
    options: ["35", "40", "45", "50"],
    correctAnswer: 1,
    explanation: "The numbers go up by 10, so 40 is next.",
  },
  {
    id: 25,
    subject: "math",
    category: "series",
    difficulty: "easy",
    question: "What number is missing: 1, 3, __, 7, 9?",
    options: ["4", "5", "6", "8"],
    correctAnswer: 1,
    explanation: "The odd numbers continue: 1, 3, 5, 7, 9.",
  },
  {
    id: 26,
    subject: "math",
    category: "challenge",
    difficulty: "easy",
    question: "Which is the biggest number?",
    options: ["18", "81", "28", "38"],
    correctAnswer: 1,
    explanation: "81 is bigger than all the other numbers.",
  },
  {
    id: 27,
    subject: "math",
    category: "challenge",
    difficulty: "easy",
    question: "How many sides does a triangle have?",
    options: ["2", "3", "4", "5"],
    correctAnswer: 1,
    explanation: "A triangle has 3 sides.",
  },
  {
    id: 28,
    subject: "math",
    category: "challenge",
    difficulty: "medium",
    question: "If today is Monday, what day is after Tuesday?",
    options: ["Monday", "Tuesday", "Wednesday", "Thursday"],
    correctAnswer: 2,
    explanation: "Wednesday comes after Tuesday.",
  },
  {
    id: 29,
    subject: "math",
    category: "challenge",
    difficulty: "easy",
    question: "Which shape is round?",
    options: ["Circle", "Square", "Triangle", "Rectangle"],
    correctAnswer: 0,
    explanation: "A circle is round.",
  },
  {
    id: 30,
    subject: "math",
    category: "challenge",
    difficulty: "easy",
    question: "What is 10 more than 20?",
    options: ["25", "30", "35", "40"],
    correctAnswer: 1,
    explanation: "20 + 10 = 30.",
  },
  {
    id: 31,
    subject: "english",
    category: "alphabet",
    difficulty: "easy",
    question: "Which letter comes after C?",
    options: ["A", "B", "D", "E"],
    correctAnswer: 2,
    explanation: "D comes after C.",
  },
  {
    id: 32,
    subject: "english",
    category: "alphabet",
    difficulty: "easy",
    question: "Which letter starts the word ‘Sun’?",
    options: ["S", "T", "C", "F"],
    correctAnswer: 0,
    explanation: "Sun starts with S.",
  },
  {
    id: 33,
    subject: "english",
    category: "alphabet",
    difficulty: "medium",
    question: "Which letter comes before M?",
    options: ["K", "L", "N", "O"],
    correctAnswer: 1,
    explanation: "L comes before M.",
  },
  {
    id: 34,
    subject: "english",
    category: "alphabet",
    difficulty: "easy",
    question: "How many letters are in the word ‘cat’?",
    options: ["2", "3", "4", "5"],
    correctAnswer: 1,
    explanation: "C-a-t has 3 letters.",
  },
  {
    id: 35,
    subject: "english",
    category: "alphabet",
    difficulty: "easy",
    question: "Which one is a vowel?",
    options: ["B", "D", "G", "A"],
    correctAnswer: 3,
    explanation: "A is a vowel.",
  },
  {
    id: 36,
    subject: "english",
    category: "spelling",
    difficulty: "easy",
    question: "Which word is spelled correctly?",
    options: ["Skool", "School", "Scool", "Sckool"],
    correctAnswer: 1,
    explanation: "School is the correct spelling.",
  },
  {
    id: 37,
    subject: "english",
    category: "spelling",
    difficulty: "easy",
    question: "Choose the missing letter: _og",
    options: ["D", "C", "B", "T"],
    correctAnswer: 0,
    explanation: "D + og makes dog.",
  },
  {
    id: 38,
    subject: "english",
    category: "spelling",
    difficulty: "medium",
    question: "Which word rhymes with ‘cake’?",
    options: ["Bike", "Lake", "Book", "Cup"],
    correctAnswer: 1,
    explanation: "Lake rhymes with cake.",
  },
  {
    id: 39,
    subject: "english",
    category: "spelling",
    difficulty: "easy",
    question: "Which word has three letters?",
    options: ["Elephant", "Tree", "Sun", "House"],
    correctAnswer: 2,
    explanation: "Sun has 3 letters.",
  },
  {
    id: 40,
    subject: "english",
    category: "spelling",
    difficulty: "easy",
    question: "Choose the missing letter: b_ll",
    options: ["a", "e", "i", "o"],
    correctAnswer: 0,
    explanation: "B-a-ll makes ball.",
  },
  {
    id: 41,
    subject: "english",
    category: "vocabulary",
    difficulty: "easy",
    question: "What is the opposite of ‘hot’?",
    options: ["Warm", "Cold", "Dry", "Bright"],
    correctAnswer: 1,
    explanation: "Cold is the opposite of hot.",
  },
  {
    id: 42,
    subject: "english",
    category: "vocabulary",
    difficulty: "easy",
    question: "Which word means ‘happy’?",
    options: ["Sad", "Glad", "Tired", "Small"],
    correctAnswer: 1,
    explanation: "Glad means happy.",
  },
  {
    id: 43,
    subject: "english",
    category: "vocabulary",
    difficulty: "medium",
    question: "A tiny house is called a…",
    options: ["Cottage", "Mountain", "River", "Garden"],
    correctAnswer: 0,
    explanation: "A cottage is a small house.",
  },
  {
    id: 44,
    subject: "english",
    category: "vocabulary",
    difficulty: "easy",
    question: "Which word describes an apple?",
    options: ["Crunchy", "Loud", "Tall", "Fast"],
    correctAnswer: 0,
    explanation: "An apple can be crunchy.",
  },
  {
    id: 45,
    subject: "english",
    category: "vocabulary",
    difficulty: "easy",
    question: "Which word means the same as ‘big’?",
    options: ["Tiny", "Large", "Slow", "Soft"],
    correctAnswer: 1,
    explanation: "Large means big.",
  },
  {
    id: 46,
    subject: "english",
    category: "grammar",
    difficulty: "easy",
    question: "Choose the correct sentence.",
    options: ["She are happy.", "She is happy.", "She am happy.", "She be happy."],
    correctAnswer: 1,
    explanation: "She is happy is correct.",
  },
  {
    id: 47,
    subject: "english",
    category: "grammar",
    difficulty: "easy",
    question: "Which word is a naming word (noun)?",
    options: ["Jump", "Blue", "Teacher", "Quickly"],
    correctAnswer: 2,
    explanation: "Teacher names a person.",
  },
  {
    id: 48,
    subject: "english",
    category: "grammar",
    difficulty: "medium",
    question: "Choose the plural of ‘box’.",
    options: ["Boxs", "Boxes", "Boxies", "Boxen"],
    correctAnswer: 1,
    explanation: "The plural of box is boxes.",
  },
  {
    id: 49,
    subject: "english",
    category: "grammar",
    difficulty: "easy",
    question: "Which word is an action word?",
    options: ["Run", "Yellow", "Pencil", "Quiet"],
    correctAnswer: 0,
    explanation: "Run is an action.",
  },
  {
    id: 50,
    subject: "english",
    category: "grammar",
    difficulty: "easy",
    question: "Pick the word that completes: ‘I ___ a book.’",
    options: ["read", "reads", "reading", "reader"],
    correctAnswer: 0,
    explanation: "I read a book is correct.",
  },
  {
    id: 51,
    subject: "english",
    category: "simple",
    difficulty: "easy",
    question: "What do we use to see?",
    options: ["Ears", "Eyes", "Hands", "Feet"],
    correctAnswer: 1,
    explanation: "We use our eyes to see.",
  },
  {
    id: 52,
    subject: "english",
    category: "simple",
    difficulty: "easy",
    question: "What colour is a banana when it is ripe?",
    options: ["Blue", "Purple", "Yellow", "Black"],
    correctAnswer: 2,
    explanation: "A ripe banana is yellow.",
  },
  {
    id: 53,
    subject: "english",
    category: "simple",
    difficulty: "medium",
    question: "Where do fish live?",
    options: ["In water", "In trees", "In clouds", "In sand"],
    correctAnswer: 0,
    explanation: "Fish live in water.",
  },
  {
    id: 54,
    subject: "english",
    category: "simple",
    difficulty: "easy",
    question: "Which one can fly?",
    options: ["Bird", "Elephant", "Turtle", "Fish"],
    correctAnswer: 0,
    explanation: "Birds can fly.",
  },
  {
    id: 55,
    subject: "english",
    category: "simple",
    difficulty: "easy",
    question: "What do we say when someone helps us?",
    options: ["Goodbye", "Please", "Thank you", "Welcome"],
    correctAnswer: 2,
    explanation: "We say thank you when someone helps us.",
  },
];

export function getQuizQuestions(subject: Subject, category: string, difficulty: Difficulty, count: number) {
  const exact = questionBank.filter(
    (question) => question.subject === subject && question.category === category && question.difficulty === difficulty,
  );
  const categoryFallback = questionBank.filter(
    (question) => question.subject === subject && question.category === category,
  );
  const subjectFallback = questionBank.filter((question) => question.subject === subject);
  const pool = exact.length >= count ? exact : categoryFallback.length ? categoryFallback : subjectFallback;

  return [...pool]
    .sort(() => Math.random() - 0.5)
    .slice(0, Math.min(count, pool.length));
}

export const mathCategories = [
  { id: "addition", label: "Addition", icon: "+", color: "coral", hint: "Make numbers grow" },
  { id: "subtraction", label: "Subtraction", icon: "−", color: "blue", hint: "Take a little away" },
  { id: "multiplication", label: "Multiplication", icon: "×", color: "yellow", hint: "Groups of numbers" },
  { id: "division", label: "Division", icon: "÷", color: "mint", hint: "Share it fairly" },
  { id: "series", label: "Number Series", icon: "123", color: "purple", hint: "Spot the pattern" },
  { id: "challenge", label: "Math Challenge", icon: "★", color: "navy", hint: "Think like a pro" },
] as const;

export const englishCategories = [
  { id: "alphabet", label: "Alphabet", icon: "ABC", color: "coral", hint: "Letters are fun" },
  { id: "spelling", label: "Spelling", icon: "✎", color: "blue", hint: "Build every word" },
  { id: "vocabulary", label: "Vocabulary", icon: "▣", color: "yellow", hint: "Grow your word bank" },
  { id: "grammar", label: "Grammar", icon: "✓", color: "mint", hint: "Make sentences shine" },
  { id: "simple", label: "Simple English", icon: "☀", color: "purple", hint: "Everyday language" },
] as const;

export const badgeCatalog = [
  { id: "first-quiz", icon: "✦", label: "First Quiz", description: "Complete your first quiz" },
  { id: "ten-correct", icon: "◎", label: "10 Correct", description: "Answer 10 questions correctly" },
  { id: "math-star", icon: "＋", label: "Math Star", description: "Complete a Math quiz" },
  { id: "english-star", icon: "A", label: "English Star", description: "Complete an English quiz" },
  { id: "streak", icon: "♨", label: "Quiz Streak", description: "Complete 3 quizzes" },
  { id: "champion", icon: "♛", label: "Quiz Champion", description: "Score 90% or more" },
] as const;
